# -*- coding: utf-8 -*-
"""GENERAR_COMPLEJOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZ2ZHIwpEQcxApxvb49sh_Z2QUs5z4qi
"""

#from google.colab import files

uploaded = files.upload()

#!pip install biopython

from Bio.PDB import PDBParser, PDBIO, Structure
import os

def combinar_pdb(enzima_file, antibiotico_file, output_file):
    parser = PDBParser(QUIET=True)
    io = PDBIO()

    # Leer enzima
    enzima = parser.get_structure("ENZ", enzima_file)

    # Leer antibiótico
    antibiotico = parser.get_structure("LIG", antibiotico_file)

    # Crear nuevo complejo combinando ambos
    complex_structure = Structure.Structure("COMPLEJO")
    model = enzima[0]
    complex_structure.add(model)

    # Asegurar que el antibiótico sea otra cadena
    for chain in antibiotico[0]:
        chain.id = "Z"  # Cambiar ID a algo distinto, por ejemplo Z
        complex_structure[0].add(chain)

    # Guardar el nuevo complejo
    io.set_structure(complex_structure)
    io.save(output_file)
    print(f"✅ Complejo guardado como: {output_file}")

# Ejemplo: combinar NDM-1 con Imipenem modificado
combinar_pdb("ndm1_fixed.pdb", "Imipenem_mod1.pdb", "ndm1_imipenem_mod1.pdb")
combinar_pdb("ndm1_fixed.pdb", "Imipenem_mod2.pdb", "ndm1_imipenem_mod2.pdb")
combinar_pdb("ndm1_fixed.pdb", "Meropenem_mod1.pdb", "ndm1_meropenem_mod1.pdb")
combinar_pdb("ndm1_fixed.pdb", "Meropenem_mod2.pdb", "ndm1_meropenem_mod2.pdb")
combinar_pdb("oxa48_fixed.pdb", "Imipenem_mod1.pdb", "oxa48_imipenem_mod1.pdb")
combinar_pdb("oxa48_fixed.pdb", "Imipenem_mod2.pdb", "oxa48_imipenem_mod2.pdb")
combinar_pdb("oxa48_fixed.pdb", "Meropenem_mod1.pdb", "oxa48_meropenem_mod1.pdb")
combinar_pdb("oxa48_fixed.pdb", "Meropenem_mod2.pdb", "oxa48_meropenem_mod2.pdb")

"""CARGAR COMPLEJOS A PLIP

INGRESA A LA WEB: https://plip-tool.biotec.tu-dresden.de/plip-web/plip/index

CARGA LOS COMPLEJOS:
1. https://plip-tool.biotec.tu-dresden.de/plip-web/plip/result/05b0d9a3-3cee-4e2e-aecc-e14cfcf634e7
2. https://plip-tool.biotec.tu-dresden.de/plip-web/plip/result/760ae523-2509-4e15-8599-31b98b1116ee
3. https://plip-tool.biotec.tu-dresden.de/plip-web/plip/result/06a6da70-eb77-4b00-828f-46aa92cb8698
4. https://plip-tool.biotec.tu-dresden.de/plip-web/plip/result/85d31029-d523-42a1-9cef-3f396a683c50
5. https://plip-tool.biotec.tu-dresden.de/plip-web/plip/result/ab427174-af6f-4c43-9346-97c33afbd40f
6. https://plip-tool.biotec.tu-dresden.de/plip-web/plip/result/4733d689-2b76-4e66-a2f0-fe30f6f7d7ee
7. https://plip-tool.biotec.tu-dresden.de/plip-web/plip/result/49ae6e36-d254-4995-abea-ffbd303c8988
8. https://plip-tool.biotec.tu-dresden.de/plip-web/plip/result/f04093a9-faa9-4975-90f5-2f058eafae28
"""